CREATE TABLE IF NOT EXISTS Category (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Product (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    CategoryId INTEGER,
    Stock INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY(CategoryId) REFERENCES Category(Id)
);

CREATE TABLE IF NOT EXISTS History (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    ProductId INTEGER NOT NULL,
    Quantity INTEGER NOT NULL,
    Type TEXT NOT NULL,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    User TEXT,
    FOREIGN KEY(ProductId) REFERENCES Product(Id)
);

CREATE TABLE IF NOT EXISTS Cart (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Orders (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    CartId INTEGER,
    ProductId INTEGER,
    Quantity INTEGER,
    FOREIGN KEY(CartId) REFERENCES Cart(Id),
    FOREIGN KEY(ProductId) REFERENCES Product(Id)
);

CREATE TABLE IF NOT EXISTS Transaction (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    CartId INTEGER,
    Total REAL,
    CreatedAt TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(CartId) REFERENCES Cart(Id)
);

CREATE TABLE IF NOT EXISTS Account (
    Username TEXT PRIMARY KEY,
    Password TEXT NOT NULL,
    Rol TEXT NOT NULL,
    NombreCompleto TEXT,
    FailedAttempts INTEGER DEFAULT 0,
    IsLocked INTEGER DEFAULT 0,
    SecurityQuestion TEXT,
    SecurityAnswer TEXT
);
